version: '3'
services:
  workshop-authentication:
    container_name: workshop-authentication
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "9292:9292"
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
