version: '3'
services:
  workshop-authentication:
    container_name: authentication-service
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:80/status || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5
